import { useCallback, useMemo } from "react";
import { Text, View, ScrollView, TouchableOpacity, Alert } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { BarChart, PieChart } from "react-native-gifted-charts";
import * as Print from "expo-print";
import { chartData } from "@/data/chart_data";
import { performanceData } from "@/data/performance_data";
import { sites } from "@/data/sites";
import type { PerformanceSlice } from "@/types";

export default function Report() {
  const barData = useMemo(
    () =>
      chartData.flatMap((month) =>
        month.days.map((day) => {
          const d = new Date(day.date);
          return {
            value: day.energyGeneratedkWh,
            label: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
            frontColor: "#4A90D9",
          };
        })
      ),
    []
  );

  const total = useMemo(
    () =>
      performanceData.overPerformingDays +
      performanceData.normalDays +
      performanceData.underPerformingDays +
      performanceData.daysNoData +
      performanceData.zeroEnergyDays,
    []
  );

  const pieData: PerformanceSlice[] = useMemo(
    () => [
      { label: "Over-performing", value: performanceData.overPerformingDays, color: "#27AE60" },
      { label: "Normal", value: performanceData.normalDays, color: "#4A90D9" },
      { label: "Under-performing", value: performanceData.underPerformingDays, color: "#E67E22" },
      { label: "No Data", value: performanceData.daysNoData, color: "#AAA" },
      { label: "Zero Energy", value: performanceData.zeroEnergyDays, color: "#E74C3C" },
    ],
    []
  );

  const siteName = sites[0]?.name ?? "N/A";
  const siteCapacity = sites[0]?.capacity ?? "";

  const handleGeneratePDF = useCallback(async () => {
    const barRows = barData
      .map((d) => `<tr><td>${d.label}</td><td>${d.value.toFixed(1)} kWh</td></tr>`)
      .join("");

    const pieRows = pieData
      .map(
        (p) =>
          `<tr>
            <td><span style="display:inline-block;width:12px;height:12px;border-radius:6px;background:${p.color};margin-right:6px;"></span>${p.label}</td>
            <td>${p.value} days (${((p.value / total) * 100).toFixed(0)}%)</td>
          </tr>`
      )
      .join("");

    const html = `
      <html>
        <head>
          <style>
            body { font-family: -apple-system, sans-serif; padding: 40px; color: #1A1A2E; }
            h1 { color: #4A90D9; font-size: 24px; }
            h2 { color: #333; font-size: 18px; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; }
            th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #EEE; }
            th { background: #F0F0F0; font-weight: 600; }
            .summary { display: flex; gap: 24px; margin-top: 12px; }
            .summary-item { flex: 1; }
            .summary-label { font-size: 12px; color: #888; }
            .summary-value { font-size: 16px; font-weight: 600; }
          </style>
        </head>
        <body>
          <h1>☀️ SolYield — Visit Report</h1>
          <div class="summary">
            <div class="summary-item"><div class="summary-label">Site Name</div><div class="summary-value">${siteName}</div></div>
            <div class="summary-item"><div class="summary-label">Technician</div><div class="summary-value">Arjun K.</div></div>
            <div class="summary-item"><div class="summary-label">Capacity</div><div class="summary-value">${siteCapacity}</div></div>
          </div>
          <h2>Daily Generation</h2>
          <table><tr><th>Date</th><th>Energy</th></tr>${barRows}</table>
          <h2>Performance Breakdown</h2>
          <table><tr><th>Category</th><th>Days</th></tr>${pieRows}</table>
          <p style="margin-top: 40px; color: #AAA; font-size: 12px;">Generated by SolYield App · ${new Date().toLocaleString()}</p>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html });
      Alert.alert("PDF Generated!", `Saved to:\n${uri}`);
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : "Unknown error";
      Alert.alert("PDF Error", message);
    }
  }, [barData, pieData, siteName, siteCapacity, total]);

  return (
    <ScrollView className="flex-1 bg-[#F8F9FA]" contentContainerClassName="p-5 pb-10">

      {/* Summary Card */}
      <View className="bg-white rounded-2xl p-5 mb-4 shadow-sm elevation-2">
        <Text className="text-lg font-bold text-[#1A1A2E] mb-3">Visit Summary</Text>
        <View className="flex-row justify-between">
          <View>
            <Text className="text-base font-semibold text-[#1A1A2E]">{siteName}</Text>
            <Text className="text-xs text-gray-400 mt-0.5">Site Name</Text>
          </View>
          <View>
            <Text className="text-base font-semibold text-[#1A1A2E]">Arjun K.</Text>
            <Text className="text-xs text-gray-400 mt-0.5">Technician</Text>
          </View>
        </View>
        <View className="flex-row justify-between mt-3">
          <View>
            <Text className="text-base font-semibold text-[#1A1A2E]">{siteCapacity}</Text>
            <Text className="text-xs text-gray-400 mt-0.5">Capacity</Text>
          </View>
          <View>
            <Text className="text-base font-semibold text-[#1A1A2E]">{barData.length} days</Text>
            <Text className="text-xs text-gray-400 mt-0.5">Data Points</Text>
          </View>
        </View>
      </View>

      {/* Bar Chart */}
      <View className="bg-white rounded-2xl p-5 mb-4 shadow-sm elevation-2">
        <Text className="text-base font-bold text-[#1A1A2E] mb-4">Daily Generation (kWh)</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          <BarChart
            data={barData}
            barWidth={28}
            spacing={14}
            roundedTop
            roundedBottom
            xAxisThickness={1}
            yAxisThickness={1}
            yAxisTextStyle={{ fontSize: 10, color: "#888" }}
            xAxisLabelTextStyle={{ fontSize: 10, color: "#888" }}
            noOfSections={5}
            barBorderRadius={4}
            frontColor="#4A90D9"
            isAnimated
          />
        </ScrollView>
      </View>

      {/* Pie Chart */}
      <View className="bg-white rounded-2xl p-5 mb-4 shadow-sm elevation-2">
        <Text className="text-base font-bold text-[#1A1A2E] mb-4">Performance Breakdown</Text>
        <View className="flex-row items-center gap-5">
          <PieChart
            data={pieData}
            donut
            radius={80}
            innerRadius={50}
            innerCircleColor="#FFF"
            centerLabelComponent={() => (
              <View className="items-center">
                <Text className="text-xl font-bold text-[#1A1A2E]">{total}</Text>
                <Text className="text-xs text-gray-400">days</Text>
              </View>
            )}
          />
          <View className="flex-1 gap-2">
            {pieData.map((p) => (
              <View key={p.label} className="flex-row items-center gap-1.5">
                <View className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: p.color }} />
                <Text className="text-xs text-gray-600 flex-1">{p.label}</Text>
                <Text className="text-xs font-semibold text-[#1A1A2E]">
                  {p.value} ({((p.value / total) * 100).toFixed(0)}%)
                </Text>
              </View>
            ))}
          </View>
        </View>
      </View>

      {/* PDF Button */}
      <TouchableOpacity
        className="bg-[#8E44AD] flex-row items-center justify-center gap-2 py-4 rounded-2xl mt-2"
        activeOpacity={0.7}
        onPress={handleGeneratePDF}
      >
        <Ionicons name="document-text-outline" size={20} color="#FFF" />
        <Text className="text-white font-bold text-base">Generate PDF Report</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}