import { useCallback, useMemo } from "react";
import { Text, View, StyleSheet, ScrollView, TouchableOpacity, Alert } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { BarChart, PieChart } from "react-native-gifted-charts";
import * as Print from "expo-print";
import * as FileSystem from "expo-file-system";
import { chartData } from "@/data/chart_data";
import { performanceData } from "@/data/performance_data";
import { sites } from "@/data/sites";
import type { PerformanceSlice } from "@/types";

export default function Report() {
  // --- Bar chart data: flatten daily generation across all months ---
  const barData = useMemo(
    () =>
      chartData.flatMap((month) =>
        month.days.map((day) => {
          const d = new Date(day.date);
          return {
            value: day.energyGeneratedkWh,
            label: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
            frontColor: "#4A90D9",
          };
        })
      ),
    []
  );

  // --- Pie chart data: performance breakdown ---
  const total = useMemo(
    () =>
      performanceData.overPerformingDays +
      performanceData.normalDays +
      performanceData.underPerformingDays +
      performanceData.daysNoData +
      performanceData.zeroEnergyDays,
    []
  );

  const pieData: PerformanceSlice[] = useMemo(
    () => [
      {
        label: "Over-performing",
        value: performanceData.overPerformingDays,
        color: "#27AE60",
      },
      {
        label: "Normal",
        value: performanceData.normalDays,
        color: "#4A90D9",
      },
      {
        label: "Under-performing",
        value: performanceData.underPerformingDays,
        color: "#E67E22",
      },
      {
        label: "No Data",
        value: performanceData.daysNoData,
        color: "#AAA",
      },
      {
        label: "Zero Energy",
        value: performanceData.zeroEnergyDays,
        color: "#E74C3C",
      },
    ],
    []
  );

  const siteName = sites[0]?.name ?? "N/A";
  const siteCapacity = sites[0]?.capacity ?? "";

  // --- PDF Generation using expo-print ---
  const handleGeneratePDF = useCallback(async () => {
    const barRows = barData
      .map(
        (d) =>
          `<tr><td>${d.label}</td><td>${d.value.toFixed(1)} kWh</td></tr>`
      )
      .join("");

    const pieRows = pieData
      .map(
        (p) =>
          `<tr>
            <td><span style="display:inline-block;width:12px;height:12px;border-radius:6px;background:${p.color};margin-right:6px;"></span>${p.label}</td>
            <td>${p.value} days (${((p.value / total) * 100).toFixed(0)}%)</td>
          </tr>`
      )
      .join("");

    const html = `
      <html>
        <head>
          <style>
            body { font-family: -apple-system, sans-serif; padding: 40px; color: #1A1A2E; }
            h1 { color: #4A90D9; font-size: 24px; }
            h2 { color: #333; font-size: 18px; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; }
            th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #EEE; }
            th { background: #F0F0F0; font-weight: 600; }
            .summary { display: flex; gap: 24px; margin-top: 12px; }
            .summary-item { flex: 1; }
            .summary-label { font-size: 12px; color: #888; }
            .summary-value { font-size: 16px; font-weight: 600; }
          </style>
        </head>
        <body>
          <h1>☀️ SolYield — Visit Report</h1>
          <div class="summary">
            <div class="summary-item">
              <div class="summary-label">Site Name</div>
              <div class="summary-value">${siteName}</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">Technician</div>
              <div class="summary-value">Arjun K.</div>
            </div>
            <div class="summary-item">
              <div class="summary-label">Capacity</div>
              <div class="summary-value">${siteCapacity}</div>
            </div>
          </div>

          <h2>Daily Generation</h2>
          <table>
            <tr><th>Date</th><th>Energy</th></tr>
            ${barRows}
          </table>

          <h2>Performance Breakdown</h2>
          <table>
            <tr><th>Category</th><th>Days</th></tr>
            ${pieRows}
          </table>

          <p style="margin-top: 40px; color: #AAA; font-size: 12px;">
            Generated by SolYield App · ${new Date().toLocaleString()}
          </p>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html });
      Alert.alert("PDF Generated!", `Saved to:\n${uri}`);
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : "Unknown error";
      Alert.alert("PDF Error", message);
    }
  }, [barData, pieData, siteName, siteCapacity, total]);

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Summary */}
      <View style={styles.summaryCard}>
        <Text style={styles.summaryTitle}>Visit Summary</Text>
        <View style={styles.summaryRow}>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{siteName}</Text>
            <Text style={styles.summaryLabel}>Site Name</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>Arjun K.</Text>
            <Text style={styles.summaryLabel}>Technician</Text>
          </View>
        </View>
        <View style={[styles.summaryRow, styles.summaryRowGap]}>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{siteCapacity}</Text>
            <Text style={styles.summaryLabel}>Capacity</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{barData.length} days</Text>
            <Text style={styles.summaryLabel}>Data Points</Text>
          </View>
        </View>
      </View>

      {/* Bar Chart — Daily Generation */}
      <View style={styles.chartCard}>
        <Text style={styles.chartTitle}>Daily Generation (kWh)</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          <BarChart
            data={barData}
            barWidth={28}
            spacing={14}
            roundedTop
            roundedBottom
            xAxisThickness={1}
            yAxisThickness={1}
            yAxisTextStyle={styles.axisText}
            xAxisLabelTextStyle={styles.axisText}
            noOfSections={5}
            barBorderRadius={4}
            frontColor="#4A90D9"
            isAnimated
          />
        </ScrollView>
      </View>

      {/* Pie Chart — Performance */}
      <View style={styles.chartCard}>
        <Text style={styles.chartTitle}>Performance Breakdown</Text>
        <View style={styles.pieContainer}>
          <PieChart
            data={pieData}
            donut
            radius={80}
            innerRadius={50}
            innerCircleColor="#FFF"
            centerLabelComponent={() => (
              <View style={styles.pieCenter}>
                <Text style={styles.pieCenterValue}>{total}</Text>
                <Text style={styles.pieCenterLabel}>days</Text>
              </View>
            )}
          />
          <View style={styles.legend}>
            {pieData.map((p) => (
              <View key={p.label} style={styles.legendRow}>
                <View style={[styles.legendDot, { backgroundColor: p.color }]} />
                <Text style={styles.legendLabel}>{p.label}</Text>
                <Text style={styles.legendValue}>
                  {p.value} ({((p.value / total) * 100).toFixed(0)}%)
                </Text>
              </View>
            ))}
          </View>
        </View>
      </View>

      {/* Generate PDF */}
      <TouchableOpacity
        style={styles.pdfButton}
        activeOpacity={0.7}
        onPress={handleGeneratePDF}
      >
        <Ionicons name="document-text-outline" size={20} color="#FFF" />
        <Text style={styles.pdfButtonText}>Generate PDF Report</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  summaryCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1A1A2E",
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryRowGap: {
    marginTop: 12,
  },
  summaryItem: {},
  summaryValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A2E",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#888",
    marginTop: 2,
  },
  chartCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1A2E",
    marginBottom: 16,
  },
  axisText: {
    fontSize: 10,
    color: "#888",
  },
  pieContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  pieCenter: {
    alignItems: "center",
  },
  pieCenterValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1A1A2E",
  },
  pieCenterLabel: {
    fontSize: 11,
    color: "#888",
  },
  legend: {
    flex: 1,
    gap: 8,
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendLabel: {
    fontSize: 12,
    color: "#444",
    flex: 1,
  },
  legendValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A2E",
  },
  pdfButton: {
    backgroundColor: "#8E44AD",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 8,
  },
  pdfButtonText: {
    color: "#FFF",
    fontWeight: "700",
    fontSize: 16,
  },
});
